#!/usr/bin/env bash
# Copies the compiled ABI into the TypeScript packages so they never read Foundry output at runtime.
set -euo pipefail
cd "$(dirname "$0")/.."
(cd contracts && forge build >/dev/null)
python3 - <<'PY'
import json, pathlib
abi = json.load(open("contracts/out/Stokvel.sol/Stokvel.json"))["abi"]
body = "// Generated by scripts/export-abi.sh from contracts/out/Stokvel.sol/Stokvel.json. Do not edit.\n"
body += "export const stokvelAbi = " + json.dumps(abi, indent=2) + " as const;\n"
for p in ["relayer/src/abi.ts", "stage/lib/abi.ts"]:
    path = pathlib.Path(p); path.parent.mkdir(parents=True, exist_ok=True); path.write_text(body)
    print("wrote", p)
PY
